### ISSUE TITLE
Podcast length 0 minutes

### ISSUE THREAD

**Issue by Siebe** [MartinMouritzen/PodcastPlayer#1]
The Podcasting 2.0 episodes all show 0 minutes. This could be something with their feed though. This also seems to prevent saving the progress (which otherwise works great!)
Using PWA with Firefox, Android 10, but also on other platforms.

https://web.podfriend.com/podcast/podcasting-202

**Comment by MartinMouritzen** [comment]
Thanks for your feedback!

Yeah, this is something with the feed for now. I changed it to a guesstimate based on file length, which is far from perfect. But (as you know) we are discussing how "we" can fix this on a podcastindex level
