### ISSUE TITLE
Remember sort by

### ISSUE THREAD

**Issue by Siebe** [MartinMouritzen/PodcastPlayer#2]
When I change sort by oldest to any other mode and browse around other podcasts,
I expect the setting to stay on the mode I set it on.
Instead it switches back to "oldest" every time a new podcast is loaded.

You *could* save this setting per podcast :p and I would suggest sorting by newest by default.

**Comment by MartinMouritzen** [comment]
Thanks for your feedback!

Yeah, this is something I want to do. I hope to work on it this weekend!

**Comment by Siebe** [comment]
Your default is still from "newest". I assume this is by design, so let me close this ticket an tyvm ;)
