### ISSUE TITLE
Unable to move cursor in search

### ISSUE THREAD

**Issue by Siebe** [MartinMouritzen/PodcastPlayer#3]
When input text in the search field and click/tap on the text, i would expect my cursor to jump to that position. That does not work... :}
In FF on both Linux and Android (PWA and in browser). 
In Chrome, Linux the cursor does jump.

**Comment by MartinMouritzen** [comment]
Hi Siebe,
I managed to reproduce this, and fixed it.

For the possible geeks reading, I had a user-select: none;" on the titlebar. In Chrome this is not inherited by input fields, in Firefox it is, which then prevents the moving of the cursor with the mouse.

**Comment by MartinMouritzen** [comment]
I will release a new version later today! :)

**Comment by MartinMouritzen** [comment]
Fix released!
